Feature/ort addition (#16)
* ORT tests for cpld_control_p7 and cpld_bmark_p7

* Modify removal of exe and module files to not affect the rt.sh files

* Fix broken ecflow run on Hera

* Add hecflow01 login node check for Hera

* Change FHMAX value in export_fv3 to work better with ORT

diff --git a/tests/opnReqTest b/tests/opnReqTest
--- a/tests/opnReqTest
+++ b/tests/opnReqTest
@@ -74,7 +74,7 @@ find_build() {
 }
 
 build_opnReqTests() {
-  rm -f fv3_*.exe modules.fv3_*
+  rm -f fv3_std.exe fv3_dbg.exe fv3_bit.exe modules.fv3_std modules.fv3_dbg modules.fv3_bit
 
   model_found=false
   base_opt=
@@ -314,10 +314,12 @@ source module-setup.sh
 # Machine-dependent libraries, modules, variables, etc.
 if [[ $MACHINE_ID = hera.* ]]; then
 
-  export PATH=/scratch1/NCEPDEV/nems/emc.nemspara/soft/miniconda3/bin:$PATH
-  export PYTHONPATH=/scratch1/NCEPDEV/nems/emc.nemspara/soft/miniconda3/lib/python3.8/site-packages
-  ECFLOW_START=/scratch1/NCEPDEV/nems/emc.nemspara/soft/miniconda3/bin/ecflow_start.sh
-  ECF_PORT=$(( $(id -u) + 1500 ))
+  PYTHONHOME=/scratch1/NCEPDEV/nems/emc.nemspara/soft/miniconda3_new_20210629
+  export PATH=$PYTHONHOME/bin:$PATH
+  export PYTHONPATH=$PYTHONHOME/lib/python3.7/site-packages
+
+  module load ecflow
+  ECFLOW_START=ecflow_start.sh
 
   PARTITION=
   QUEUE=batch
@@ -517,7 +519,8 @@ mkdir -p ${RUNDIR_ROOT}
 
 if [[ $ECFLOW == true ]]; then
   ECFLOW_RUN=${PATHRT}/ecflow_opnReqTest_run
-  ECFLOW_SUITE=opnreqtest
+  ECFLOW_SUITE=opnreqtest_$$
+  COMPILE_PREV_WW3_NR=
   rm -rf ${ECFLOW_RUN}
   mkdir -p ${ECFLOW_RUN}/${ECFLOW_SUITE}
   cp head.h tail.h ${ECFLOW_RUN}
@@ -528,6 +531,7 @@ if [[ $ECFLOW == true ]]; then
 		edit ECF_INCLUDE '${ECFLOW_RUN}'
 		edit ECF_KILL_CMD kill -15 %ECF_RID% > %ECF_JOB%.kill 2>&1
 		edit ECF_TRIES 1
+		label src_dir '{$PATHTR}'
 		label rundir_root '${RUNDIR_ROOT}'
 		limit max_builds 6
 		limit max_jobs 30
@@ -541,6 +545,12 @@ if [[ $ECFLOW == true ]]; then
   else
     error "ecflow is not supported on this machine $MACHINE_ID"
   fi
+
+  if [[ $MACHINE_ID == hera.* ]] && [[ ! $HOSTNAME == hecflow* ]]; then
+    echo "ERROR: To use ECFlow on Hera please use the 'hecflow01' login node: ssh hecflow01."
+    exit 1
+  fi
+
 fi
 
 opnreqtest_log=${PATHRT}/OpnReqTests_$MACHINE_ID.log
