Update regression test configs for HWRF physics, add new test fv3_ccpp_HAFS_v0_hwrf_thompson

diff --git a/tests/fv3_conf/ccpp_HAFS_v0_hwrf_run.IN b/tests/fv3_conf/ccpp_HAFS_v0_hwrf_run.IN
--- a/tests/fv3_conf/ccpp_HAFS_v0_hwrf_run.IN
+++ b/tests/fv3_conf/ccpp_HAFS_v0_hwrf_run.IN
@@ -1,10 +1,20 @@
 rm -fr INPUT RESTART
-if [ $WARM_START = .F. ]; then
-  cp -r @[RTPWD]/FV3_input_data/INPUT .
-  mkdir RESTART
-else
-  mkdir INPUT RESTART
-  cp -r @[RTPWD]/FV3_input_data/RESTART/* ./INPUT
+mkdir INPUT RESTART
+if [ $IMP_PHYSICS = 8 ]; then
+  if [ $WARM_START = .F. ]; then
+    cp -r @[RTPWD]/FV3_input_data_gsd/FV3_input_data_C96_with_aerosols/* INPUT/
+  else
+    cp -r @[RTPWD]/FV3_input_data_gsd/FV3_input_data_C96_with_aerosols/grid_spec*.nc INPUT/
+    cp -r @[RTPWD]/FV3_input_data_gsd/FV3_input_data_C96_with_aerosols/C96_grid*.nc INPUT/
+    cp -r @[RTPWD]/FV3_input_data_gsd/FV3_input_data_C96_with_aerosols/oro_data*.nc INPUT/
+    cp ../fv3_ccpp_gsd_coldstart${RT_SUFFIX}/RESTART/* INPUT/
+  fi
+elif [ $IMP_PHYSICS = 15 ]; then
+  if [ $WARM_START = .F. ]; then
+    cp -r @[RTPWD]/FV3_input_data/INPUT INPUT/
+  else
+    cp -r @[RTPWD]/FV3_input_data/RESTART/* ./INPUT/
+  fi
 fi
 
 cp    @[RTPWD]/FV3_input_data/INPUT/aerosol.dat .
@@ -16,24 +26,66 @@ cp    @[RTPWD]/FV3_input_data/global_h2o_pltc.f77 ./global_h2oprdlos.f77
 cp    @[RTPWD]/FV3_input_data/*grb .
 cp    @[RTPWD]/FV3_input_data/*_table .
 cp    @[RTPWD]/FV3_input_data/*configure .
-cp    @[RTPWD]/FV3_input_data_hafs/GENPARM.TBL .
-cp    @[RTPWD]/FV3_input_data_hafs/SOILPARM.TBL .
-cp    @[RTPWD]/FV3_input_data_hafs/VEGPARM.TBL .
+
+
+if [[ $MACHINE_ID = cheyenne.* ]]; then
+  HAFS_TMP_INPUT_DIR=/glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/FV3_input_data_temporary_hafs
+elif [[ $MACHINE_ID = hera.* ]]; then
+  HAFS_TMP_INPUT_DIR=/scratch1/BMC/gmtb/ufs-weather-model/RT/NEMSfv3gfs/FV3_input_data_temporary_hafs
+else
+  HAFS_TMP_INPUT_DIR=/nonexistentdir
+fi
+
+# Copy landuse/soil/vegetation parameter tables for HWRF Noah LSM
+#cp    @[RTPWD]/FV3_input_data_hafs/GENPARM.TBL .
+#cp    @[RTPWD]/FV3_input_data_hafs/SOILPARM.TBL .
+#cp    @[RTPWD]/FV3_input_data_hafs/VEGPARM.TBL .
+cp     $HAFS_TMP_INPUT_DIR/GENPARM.TBL .
+cp     $HAFS_TMP_INPUT_DIR/SOILPARM.TBL .
+cp     $HAFS_TMP_INPUT_DIR/VEGPARM.TBL .
 
 # Copy diag table for HWRF RRTMG or GFS RRTMG
 if [ $IOVR_LW = 4 ] && [ $IOVR_SW = 4 ]; then
-    cp @[RTPWD]/FV3_input_data_hafs/diag_table_FA_HWRF diag_table
+  #cp @[RTPWD]/FV3_input_data_hafs/diag_table_FA_HWRF diag_table
+  cp $HAFS_TMP_INPUT_DIR/diag_table_FA_HWRF diag_table
 else
-    cp @[RTPWD]/FV3_input_data_hafs/diag_table_FA diag_table
+  #cp @[RTPWD]/FV3_input_data_hafs/diag_table_FA diag_table
+  cp $HAFS_TMP_INPUT_DIR/diag_table_FA diag_table
 fi
-# Copy field table for Ferrier-Aligo MP
-cp @[RTPWD]/FV3_input_data_hafs/field_table_FA_nwat4 field_table
 
-cp @[RTPWD]/FV3_input_data/DETAMPNEW_DATA* .
+# Copy field table, depending on microphysics choice and whether MYNN/SATMEDMF is used
+if [ $IMP_PHYSICS = 8 ]; then
+  if [ $LTAEROSOL = .T. ]; then
+    if [ $DO_MYNNEDMF = .T. ] || [ $SATMEDMF = .T. ]; then
+      cp  @[RTPWD]/FV3_input_data_gsd/field_table_gsd field_table
+    else
+      cp  @[RTPWD]/FV3_input_data_gsd/field_table_gf_thompson field_table
+    fi
+  else
+    if [ $DO_MYNNEDMF = .T. ] || [ $SATMEDMF = .T. ]; then
+      echo "ERROR, no field table configured for Thompson MP without aerosols but with MYNN or SATMEDMF (need TKE)"
+      exit 1
+    else
+      cp  @[RTPWD]/FV3_input_data_gsd/field_table_thompson_noaero field_table
+    fi
+  fi
+elif [ $IMP_PHYSICS = 15 ]; then
+  # Copy field table for Ferrier-Aligo MP
+  #cp @[RTPWD]/FV3_input_data_hafs/field_table_FA_nwat4 field_table
+  cp $HAFS_TMP_INPUT_DIR/field_table_FA_nwat4 field_table
+else
+  echo "ERROR, no field table configured for IMP_PHYSICS=${IMP_PHYSICS}"
+  exit 1
+fi
+
+# Thompson or F-A MP lookup tables
+if [ $IMP_PHYSICS = 8 ]; then
+  cp @[RTPWD]/FV3_input_data_gsd/qr_acr_qs.dat .
+  cp @[RTPWD]/FV3_input_data_gsd/qr_acr_qg.dat .
+  cp @[RTPWD]/FV3_input_data_gsd/freezeH2O.dat .
+  cp @[RTPWD]/FV3_input_data_gsd/CCN_ACTIVATE.BIN .
+elif [ $IMP_PHYSICS = 15 ]; then
+  cp @[RTPWD]/FV3_input_data/DETAMPNEW_DATA* .
+fi
 
 cp ${PATHRT}/../FV3/ccpp/suites/suite_${CCPP_SUITE}.xml suite_${CCPP_SUITE}.xml
-
-# DH* 2020-06-19 Note that the FV3_input_data_hafs is not part of the official EMC baseline.
-# on hera:     /scratch1/BMC/gmtb/ufs-weather-model/RT/NEMSfv3gfs/hwrf-physics-20200618/INTEL/FV3_input_data_hafs/
-# on cheyenne: /glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/hwrf-physics-20200618/{INTEL,GNU}/FV3_input_data_hafs/
-# *DH 2020-06-19
