Update regression tests for SRW App release, part 1

diff --git a/tests/fv3_conf/ccpp_regional_run.IN b/tests/fv3_conf/ccpp_regional_run.IN
--- a/tests/fv3_conf/ccpp_regional_run.IN
+++ b/tests/fv3_conf/ccpp_regional_run.IN
@@ -1,33 +1,39 @@
-rsync -arv @[RTPWD]/FV3_regional_input_data/. .
-rsync -arv @[RTPWD]/fv3_regional_control/model_configure .
-
-rm -rf INPUT RESTART
-mkdir  INPUT RESTART
-
-rsync -arv @[RTPWD]/fv3_regional_control/INPUT/. INPUT/.
-
+rm -fr INPUT RESTART
+mkdir INPUT RESTART
+rsync -av @[RTPWD]/FV3_input_data_regional/ ./
 if [ $WARM_START = .T. ]; then
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.coupler.res             INPUT/coupler.res
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.fv_core.res.nc          INPUT/fv_core.res.nc
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.fv_core.res.tile1.nc    INPUT/fv_core.res.tile1.nc
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.fv_srf_wnd.res.tile1.nc INPUT/fv_srf_wnd.res.tile1.nc
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.fv_tracer.res.tile1.nc  INPUT/fv_tracer.res.tile1.nc
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.phy_data.nc             INPUT/phy_data.nc
-    cp ../fv3_ccpp_regional_control${RT_SUFFIX}/RESTART/20181015.120000.sfc_data.nc             INPUT/sfc_data.nc
-fi
-if [ $WRITE_RESTART_WITH_BCS = .true. ]; then
-    cp @[RTPWD]/fv3_regional_control/RESTART/fv_core.res.tile1_new.nc          RESTART/fv_core.res.tile1_new.nc
-    cp @[RTPWD]/fv3_regional_control/RESTART/fv_tracer.res.tile1_new.nc        RESTART/fv_tracer.res.tile1_new.nc
+  cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/RESTART/* INPUT/
 fi
 
-
-if [ $OZ_PHYS_NEW = .T. ]; then
-  cp  @[RTPWD]/FV3_input_data/ozprdlos_2015_new_sbuvO3_tclm15_nuchem.f77 ./global_o3prdlos.f77
-elif [ $OZ_PHYS_OLD = .T. ]; then
-  cp  @[RTPWD]/FV3_input_data/INPUT/global_o3prdlos.f77 .
+# Copy field table, depending on microphysics choice
+if [ $IMP_PHYSICS = 8 ]; then
+  ln -sf diag_table.thompson diag_table
+elif [ $IMP_PHYSICS = 11 ]; then
+  ln -sf diag_table.gfdlmp diag_table
+else
+  echo "ERROR, no diag table configured for IMP_PHYSICS=${IMP_PHYSICS}"
+  exit 1
 fi
-if [ $H2O_PHYS = .T. ]; then
-  cp  @[RTPWD]/FV3_input_data/global_h2o_pltc.f77 ./global_h2oprdlos.f77
-fi
 
-cp ${PATHRT}/../FV3/ccpp/suites/suite_${CCPP_SUITE}.xml suite_${CCPP_SUITE}.xml
+# Copy field table, depending on microphysics choice and whether MYNN/SATMEDMF is used
+if [ $IMP_PHYSICS = 8 ]; then
+  if [ $LTAEROSOL = .T. ]; then
+    if [ $DO_MYNNEDMF = .T. ] || [ $SATMEDMF = .T. ]; then
+      cp  @[RTPWD]/FV3_input_data_gsd/field_table_gsd field_table
+    else
+      cp  @[RTPWD]/FV3_input_data_gsd/field_table_gf_thompson field_table
+    fi
+  else
+    if [ $DO_MYNNEDMF = .T. ] || [ $SATMEDMF = .T. ]; then
+      echo "ERROR, no field table configured for Thompson MP without aerosols but with MYNN or SATMEDMF (need TKE)"
+      exit 1
+    else
+      cp  @[RTPWD]/FV3_input_data_gsd/field_table_thompson_noaero field_table
+    fi
+  fi
+elif [ $IMP_PHYSICS = 11 ]; then
+  cp @[RTPWD]/FV3_input_data/field_table_gfdlmp field_table
+else
+  echo "ERROR, no field table configured for IMP_PHYSICS=${IMP_PHYSICS}"
+  exit 1
+fi
