release/public-v2: b4b reproducibility for restart runs (#417)
* Add coldstart and warmstart test for global fv3_ccpp_gfs_v15p2
* coldstart and warmstart test for global fv3_ccpp_rrfs_v1alpha
* Update .gitmodules and submodule pointer for fv3atm for code review and testing
* Add regional restart tests and update regression test baseline date tag
* Regression test log for orion.intel, hera.intel, cheyenne.intel, cheyenne.gnu,jet.intel, gaea.intel

diff --git a/tests/fv3_conf/ccpp_regional_run.IN b/tests/fv3_conf/ccpp_regional_run.IN
--- a/tests/fv3_conf/ccpp_regional_run.IN
+++ b/tests/fv3_conf/ccpp_regional_run.IN
@@ -2,9 +2,18 @@ rm -fr INPUT RESTART
 mkdir INPUT RESTART
 rsync -av @[RTPWD]/FV3_input_data_regional/ ./
 if [ $WARM_START = .T. ]; then
-  cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/RESTART/* INPUT/
-  cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/INPUT/gfs_bndy.tile7.*.nc INPUT/
-  cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/INPUT/oro_data.tile7.halo4.nc INPUT/
+  if [ $CCPP_SUITE = FV3_RRFS_v1alpha ]; then
+    cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/RESTART/* INPUT/
+    cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/INPUT/gfs_bndy.tile7.*.nc INPUT/
+    cp ../fv3_ccpp_regional_coldstart${RT_SUFFIX}/INPUT/oro_data.tile7.halo4.nc INPUT/
+  elif [ $CCPP_SUITE = FV3_GFS_v15p2 ]; then
+    cp ../fv3_ccpp_regional_v15p2_coldstart${RT_SUFFIX}/RESTART/* INPUT/
+    cp ../fv3_ccpp_regional_v15p2_coldstart${RT_SUFFIX}/INPUT/gfs_bndy.tile7.*.nc INPUT/
+    cp ../fv3_ccpp_regional_v15p2_coldstart${RT_SUFFIX}/INPUT/oro_data.tile7.halo4.nc INPUT/
+  else
+    echo "ERROR, warm start runs not configured for CCPP_SUITE=${CCPP_SUITE}"
+    exit 1
+  fi
 fi
 
 # Copy field table, depending on microphysics choice
